# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c9d6e209fe152afc7f606562d16add9c1dafd14f2b1741e2b18542a32d1ddd33094ee721a3185ce1c602f8c081f1e1a5b0b13ae0f524954f07137d4bf0a2111

test:
  secret_key_base: e5b8365cd6707cf7978669864a8e400337720ab910a389da8327644399d457345b1b70ff537a3d0d23ee5a75dffa95a53e16ff565357db5923adb68137ea008f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
